[package]
name = "panic-to-result-usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-to-result-macro = { path = "../panic-to-result-macro" }

[dev-dependencies]
trybuild = "1.0.90"
